[project]
name = "enunu_training_kit"
version = "2.0.0"

[tool.ruff]
target-version = 'py312'
line-length = 99

[tool.ruff.lint]
ignore = ['I001', 'C901', 'S101', 'T2', 'PTH', 'D', 'ANN', 'Q000', 'RET504']
select = ['ALL']

[tool.ruff.format]
line-ending = 'lf'
quote-style = 'single'
